@url= http://localhost:3041/api/v1

### Sign Up
POST {{url}}/shop/signup
Content-Type: application/json

{
    "name": "Shop 45223",
    "email": "admin125222221@gmail.com",
    "password": "12345322"
}
